//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.AssCommonResource", typeof(AssCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow mail redirect.
        /// </summary>
        public static string AllowMailRedirect {
            get {
                return ResourceManager.GetString("AllowMailRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Date.
        /// </summary>
        public static string Approve_DT {
            get {
                return ResourceManager.GetString("Approve_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes: all (*) field is required to fill in.
        /// </summary>
        public static string Asterisk {
            get {
                return ResourceManager.GetString("Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Status.
        /// </summary>
        public static string Auth_Status {
            get {
                return ResourceManager.GetString("Auth_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expose author name in posts.
        /// </summary>
        public static string Authorname {
            get {
                return ResourceManager.GetString("Authorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the user to show his name in blog posts.
        /// </summary>
        public static string AuthornameNote {
            get {
                return ResourceManager.GetString("AuthornameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baby.
        /// </summary>
        public static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Settings.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete chat history.
        /// </summary>
        public static string ChatSettingsdelete {
            get {
                return ResourceManager.GetString("ChatSettingsdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off notifications.
        /// </summary>
        public static string ChatSettingsnotifications {
            get {
                return ResourceManager.GetString("ChatSettingsnotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me as online.
        /// </summary>
        public static string ChatSettingsonline {
            get {
                return ResourceManager.GetString("ChatSettingsonline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker ID.
        /// </summary>
        public static string Checker_ID {
            get {
                return ResourceManager.GetString("Checker_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class overview.
        /// </summary>
        public static string ClassOverview {
            get {
                return ResourceManager.GetString("ClassOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create_DT.
        /// </summary>
        public static string Create_DT {
            get {
                return ResourceManager.GetString("Create_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this user from Role.
        /// </summary>
        public static string DeletethisuserfromRole {
            get {
                return ResourceManager.GetString("DeletethisuserfromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Enteremail {
            get {
                return ResourceManager.GetString("Enteremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export reports.
        /// </summary>
        public static string ExportReports {
            get {
                return ResourceManager.GetString("ExportReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Repository.
        /// </summary>
        public static string FoodRepository {
            get {
                return ResourceManager.GetString("FoodRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string Forgotpass {
            get {
                return ResourceManager.GetString("Forgotpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnitures.
        /// </summary>
        public static string Furnitures {
            get {
                return ResourceManager.GetString("Furnitures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some information about this general settings option.
        /// </summary>
        public static string GeneralSettingNote {
            get {
                return ResourceManager.GetString("GeneralSettingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Roles for this User.
        /// </summary>
        public static string GetRolesforthisUser {
            get {
                return ResourceManager.GetString("GetRolesforthisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade &amp; Class.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Overview.
        /// </summary>
        public static string GradeOverview {
            get {
                return ResourceManager.GetString("GradeOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients overview.
        /// </summary>
        public static string IngredientsOverview {
            get {
                return ResourceManager.GetString("IngredientsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Types.
        /// </summary>
        public static string IngredientType {
            get {
                return ResourceManager.GetString("IngredientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inout.
        /// </summary>
        public static string Inout {
            get {
                return ResourceManager.GetString("Inout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kid Management.
        /// </summary>
        public static string KidManagement {
            get {
                return ResourceManager.GetString("KidManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        public static string Kindergarten {
            get {
                return ResourceManager.GetString("Kindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System DeKidz.
        /// </summary>
        public static string KindergartenManagerment {
            get {
                return ResourceManager.GetString("KindergartenManagerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string lbl_staff {
            get {
                return ResourceManager.GetString("lbl_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string lblapproval {
            get {
                return ResourceManager.GetString("lblapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson program.
        /// </summary>
        public static string LessonProgram {
            get {
                return ResourceManager.GetString("LessonProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List roles for user.
        /// </summary>
        public static string Listrolesforuser {
            get {
                return ResourceManager.GetString("Listrolesforuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        public static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category.
        /// </summary>
        public static string MainCategory {
            get {
                return ResourceManager.GetString("MainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker ID.
        /// </summary>
        public static string Maker_ID {
            get {
                return ResourceManager.GetString("Maker_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other sets of options are available.
        /// </summary>
        public static string NoteAllowMailRedirect {
            get {
                return ResourceManager.GetString("NoteAllowMailRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritious Management.
        /// </summary>
        public static string Nutritious {
            get {
                return ResourceManager.GetString("Nutritious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritious Information.
        /// </summary>
        public static string NutritiousInfo {
            get {
                return ResourceManager.GetString("NutritiousInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical infomation.
        /// </summary>
        public static string Physicalinf {
            get {
                return ResourceManager.GetString("Physicalinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        public static string Record_Status {
            get {
                return ResourceManager.GetString("Record_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new membership.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report panel usage.
        /// </summary>
        public static string Reportpanelusage {
            get {
                return ResourceManager.GetString("Reportpanelusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Requestcheckemail {
            get {
                return ResourceManager.GetString("Requestcheckemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string RequestConfirmPassword {
            get {
                return ResourceManager.GetString("RequestConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string RequestCreateAccount {
            get {
                return ResourceManager.GetString("RequestCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string RequestDelete {
            get {
                return ResourceManager.GetString("RequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be longer than 50 characters.
        /// </summary>
        public static string RequestLengthString {
            get {
                return ResourceManager.GetString("RequestLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string RequestLogin {
            get {
                return ResourceManager.GetString("RequestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove role from user.
        /// </summary>
        public static string RequestRemoveRoleUser {
            get {
                return ResourceManager.GetString("RequestRemoveRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms.
        /// </summary>
        public static string Requestterms {
            get {
                return ResourceManager.GetString("Requestterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenues and expenditures.
        /// </summary>
        public static string Revenueandexpenditures {
            get {
                return ResourceManager.GetString("Revenueandexpenditures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role add to user.
        /// </summary>
        public static string RoleAddToUser {
            get {
                return ResourceManager.GetString("RoleAddToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role create.
        /// </summary>
        public static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role index.
        /// </summary>
        public static string RoleIndex {
            get {
                return ResourceManager.GetString("RoleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles for this user.
        /// </summary>
        public static string Rolesforthisuser {
            get {
                return ResourceManager.GetString("Rolesforthisuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Authenticate Status.
        /// </summary>
        public static string SaveAuth {
            get {
                return ResourceManager.GetString("SaveAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Overview.
        /// </summary>
        public static string StudentOverview {
            get {
                return ResourceManager.GetString("StudentOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Progress.
        /// </summary>
        public static string TasksProgress {
            get {
                return ResourceManager.GetString("TasksProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach Management.
        /// </summary>
        public static string Teach {
            get {
                return ResourceManager.GetString("Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach schedule.
        /// </summary>
        public static string TeachSchedule {
            get {
                return ResourceManager.GetString("TeachSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseLocalAccount {
            get {
                return ResourceManager.GetString("UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
