//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Page not found..
        /// </summary>
        public static string Header_404 {
            get {
                return ResourceManager.GetString("Header_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string Header_500 {
            get {
                return ResourceManager.GetString("Header_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the page you were looking for. Meanwhile, you may.
        /// </summary>
        public static string Sugest_1_404 {
            get {
                return ResourceManager.GetString("Sugest_1_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will work on fixing that right away. Meanwhile, you may.
        /// </summary>
        public static string Sugest_1_500 {
            get {
                return ResourceManager.GetString("Sugest_1_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to dashboard.
        /// </summary>
        public static string Sugest_2_404 {
            get {
                return ResourceManager.GetString("Sugest_2_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to dashboard.
        /// </summary>
        public static string Sugest_2_500 {
            get {
                return ResourceManager.GetString("Sugest_2_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or try using the search form..
        /// </summary>
        public static string Sugest_3_404 {
            get {
                return ResourceManager.GetString("Sugest_3_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or try using the search form..
        /// </summary>
        public static string Sugest_3_500 {
            get {
                return ResourceManager.GetString("Sugest_3_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Error Page.
        /// </summary>
        public static string Title_404 {
            get {
                return ResourceManager.GetString("Title_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Error Page.
        /// </summary>
        public static string Title_500 {
            get {
                return ResourceManager.GetString("Title_500", resourceCulture);
            }
        }
    }
}
