//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IngredientsCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientsCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.IngredientsCommonResource", typeof(IngredientsCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new ingredient info.
        /// </summary>
        public static string CreateFood {
            get {
                return ResourceManager.GetString("CreateFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new ingredient type info.
        /// </summary>
        public static string CreateType {
            get {
                return ResourceManager.GetString("CreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string DonViTinh {
            get {
                return ResourceManager.GetString("DonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GiaThanh {
            get {
                return ResourceManager.GetString("GiaThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        public static string MkCalci {
            get {
                return ResourceManager.GetString("MkCalci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphor.
        /// </summary>
        public static string MkPhotpho {
            get {
                return ResourceManager.GetString("MkPhotpho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string MkSat {
            get {
                return ResourceManager.GetString("MkSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calo Energy.
        /// </summary>
        public static string NangLuongCalo {
            get {
                return ResourceManager.GetString("NangLuongCalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is from animal.
        /// </summary>
        public static string NguonTuDongVat {
            get {
                return ResourceManager.GetString("NguonTuDongVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Group.
        /// </summary>
        public static string NhomThucPham {
            get {
                return ResourceManager.GetString("NhomThucPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to kg.
        /// </summary>
        public static string QuyDoiVeKq {
            get {
                return ResourceManager.GetString("QuyDoiVeKq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Name.
        /// </summary>
        public static string TenThucPham {
            get {
                return ResourceManager.GetString("TenThucPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellulose.
        /// </summary>
        public static string TphhCellulose {
            get {
                return ResourceManager.GetString("TphhCellulose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        public static string TphhCholesterol {
            get {
                return ResourceManager.GetString("TphhCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucid.
        /// </summary>
        public static string TphhGlucid {
            get {
                return ResourceManager.GetString("TphhGlucid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipid.
        /// </summary>
        public static string TphhLipid {
            get {
                return ResourceManager.GetString("TphhLipid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string TphhNuoc {
            get {
                return ResourceManager.GetString("TphhNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protid.
        /// </summary>
        public static string TphhProtid {
            get {
                return ResourceManager.GetString("TphhProtid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorb Rate.
        /// </summary>
        public static string TyLeHapThu {
            get {
                return ResourceManager.GetString("TyLeHapThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminate Rate.
        /// </summary>
        public static string TyLeThai {
            get {
                return ResourceManager.GetString("TyLeThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin A.
        /// </summary>
        public static string VitaminA {
            get {
                return ResourceManager.GetString("VitaminA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B1.
        /// </summary>
        public static string VitaminB1 {
            get {
                return ResourceManager.GetString("VitaminB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B2.
        /// </summary>
        public static string VitaminB2 {
            get {
                return ResourceManager.GetString("VitaminB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        public static string VitaminC {
            get {
                return ResourceManager.GetString("VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caroten.
        /// </summary>
        public static string VitaminCaroten {
            get {
                return ResourceManager.GetString("VitaminCaroten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin PP.
        /// </summary>
        public static string VitaminPP {
            get {
                return ResourceManager.GetString("VitaminPP", resourceCulture);
            }
        }
    }
}
