//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InOutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InOutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.InOutResource", typeof(InOutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out Budget.
        /// </summary>
        public static string InOut_Budget {
            get {
                return ResourceManager.GetString("InOut_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out code.
        /// </summary>
        public static string InOut_Code {
            get {
                return ResourceManager.GetString("InOut_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out date.
        /// </summary>
        public static string InOut_Date {
            get {
                return ResourceManager.GetString("InOut_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out ID.
        /// </summary>
        public static string InOut_ID {
            get {
                return ResourceManager.GetString("InOut_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out paid.
        /// </summary>
        public static string InOut_Paid {
            get {
                return ResourceManager.GetString("InOut_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out reason.
        /// </summary>
        public static string InOut_Reason {
            get {
                return ResourceManager.GetString("InOut_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In out received.
        /// </summary>
        public static string InOut_Received {
            get {
                return ResourceManager.GetString("InOut_Received", resourceCulture);
            }
        }
    }
}
