//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.InResource", typeof(InResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string Customer_ID {
            get {
                return ResourceManager.GetString("Customer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Trade In.
        /// </summary>
        public static string Date_Trade_In {
            get {
                return ResourceManager.GetString("Date_Trade_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Code.
        /// </summary>
        public static string In_Code {
            get {
                return ResourceManager.GetString("In_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Debt.
        /// </summary>
        public static string In_Debt {
            get {
                return ResourceManager.GetString("In_Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In ID.
        /// </summary>
        public static string In_ID {
            get {
                return ResourceManager.GetString("In_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Reason.
        /// </summary>
        public static string In_Reason {
            get {
                return ResourceManager.GetString("In_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Received.
        /// </summary>
        public static string In_Received {
            get {
                return ResourceManager.GetString("In_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Status.
        /// </summary>
        public static string In_Status {
            get {
                return ResourceManager.GetString("In_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Total.
        /// </summary>
        public static string In_Total {
            get {
                return ResourceManager.GetString("In_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer Address.
        /// </summary>
        public static string Payer_Address {
            get {
                return ResourceManager.GetString("Payer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer Name.
        /// </summary>
        public static string Payer_Name {
            get {
                return ResourceManager.GetString("Payer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Fee.
        /// </summary>
        public static string School_Fee {
            get {
                return ResourceManager.GetString("School_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
