//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NationCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NationCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.NationCommonResource", typeof(NationCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghan / Afghani.
        /// </summary>
        public static string Afghan {
            get {
                return ResourceManager.GetString("Afghan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algerian.
        /// </summary>
        public static string Algerian {
            get {
                return ResourceManager.GetString("Algerian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string American {
            get {
                return ResourceManager.GetString("American", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angolan.
        /// </summary>
        public static string Angolan {
            get {
                return ResourceManager.GetString("Angolan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine / Argentinian.
        /// </summary>
        public static string Argentine {
            get {
                return ResourceManager.GetString("Argentine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian.
        /// </summary>
        public static string Australian {
            get {
                return ResourceManager.GetString("Australian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austrian.
        /// </summary>
        public static string Austrian {
            get {
                return ResourceManager.GetString("Austrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladeshi.
        /// </summary>
        public static string Bangladeshi {
            get {
                return ResourceManager.GetString("Bangladeshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        public static string Belarusian {
            get {
                return ResourceManager.GetString("Belarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgian.
        /// </summary>
        public static string Belgian {
            get {
                return ResourceManager.GetString("Belgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivian.
        /// </summary>
        public static string Bolivian {
            get {
                return ResourceManager.GetString("Bolivian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswanan.
        /// </summary>
        public static string Botswanan {
            get {
                return ResourceManager.GetString("Botswanan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian.
        /// </summary>
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodian.
        /// </summary>
        public static string Cambodian {
            get {
                return ResourceManager.GetString("Cambodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian.
        /// </summary>
        public static string Canadian {
            get {
                return ResourceManager.GetString("Canadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean.
        /// </summary>
        public static string Chilean {
            get {
                return ResourceManager.GetString("Chilean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian.
        /// </summary>
        public static string Colombian {
            get {
                return ResourceManager.GetString("Colombian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congolese.
        /// </summary>
        public static string Congolese {
            get {
                return ResourceManager.GetString("Congolese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuban.
        /// </summary>
        public static string Cuban {
            get {
                return ResourceManager.GetString("Cuban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypriot.
        /// </summary>
        public static string Cypriot {
            get {
                return ResourceManager.GetString("Cypriot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuadorian.
        /// </summary>
        public static string Ecuadorian {
            get {
                return ResourceManager.GetString("Ecuadorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian.
        /// </summary>
        public static string Egyptian {
            get {
                return ResourceManager.GetString("Egyptian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British / English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string Estonian {
            get {
                return ResourceManager.GetString("Estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopian.
        /// </summary>
        public static string Ethiopian {
            get {
                return ResourceManager.GetString("Ethiopian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fijian.
        /// </summary>
        public static string Fijian {
            get {
                return ResourceManager.GetString("Fijian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino.
        /// </summary>
        public static string Filipino {
            get {
                return ResourceManager.GetString("Filipino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string Georgian {
            get {
                return ResourceManager.GetString("Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghanaian.
        /// </summary>
        public static string Ghanaian {
            get {
                return ResourceManager.GetString("Ghanaian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemalan.
        /// </summary>
        public static string Guatemalan {
            get {
                return ResourceManager.GetString("Guatemalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string Icelandic {
            get {
                return ResourceManager.GetString("Icelandic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        public static string Indian {
            get {
                return ResourceManager.GetString("Indian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iranian.
        /// </summary>
        public static string Iranian {
            get {
                return ResourceManager.GetString("Iranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraqi.
        /// </summary>
        public static string Iraqi {
            get {
                return ResourceManager.GetString("Iraqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli.
        /// </summary>
        public static string Israeli {
            get {
                return ResourceManager.GetString("Israeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivorian.
        /// </summary>
        public static string Ivorian {
            get {
                return ResourceManager.GetString("Ivorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican.
        /// </summary>
        public static string Jamaican {
            get {
                return ResourceManager.GetString("Jamaican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanian.
        /// </summary>
        public static string Jordanian {
            get {
                return ResourceManager.GetString("Jordanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh / Kazakhstani.
        /// </summary>
        public static string Kazakh {
            get {
                return ResourceManager.GetString("Kazakh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenyan.
        /// </summary>
        public static string Kenyan {
            get {
                return ResourceManager.GetString("Kenyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwaiti.
        /// </summary>
        public static string Kuwaiti {
            get {
                return ResourceManager.GetString("Kuwaiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laotian / Lao.
        /// </summary>
        public static string Laotian {
            get {
                return ResourceManager.GetString("Laotian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese.
        /// </summary>
        public static string Lebanese {
            get {
                return ResourceManager.GetString("Lebanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libyan.
        /// </summary>
        public static string Libyan {
            get {
                return ResourceManager.GetString("Libyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string Lithuanian {
            get {
                return ResourceManager.GetString("Lithuanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malagasy.
        /// </summary>
        public static string Malagasy {
            get {
                return ResourceManager.GetString("Malagasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        public static string Malaysian {
            get {
                return ResourceManager.GetString("Malaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican.
        /// </summary>
        public static string Mexican {
            get {
                return ResourceManager.GetString("Mexican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroccan.
        /// </summary>
        public static string Moroccan {
            get {
                return ResourceManager.GetString("Moroccan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambican.
        /// </summary>
        public static string Mozambican {
            get {
                return ResourceManager.GetString("Mozambican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibian.
        /// </summary>
        public static string Namibian {
            get {
                return ResourceManager.GetString("Namibian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepalese / Nepali.
        /// </summary>
        public static string Nepalese {
            get {
                return ResourceManager.GetString("Nepalese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        public static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian.
        /// </summary>
        public static string Nigerian {
            get {
                return ResourceManager.GetString("Nigerian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British / Northern Irish.
        /// </summary>
        public static string NorthernIrish {
            get {
                return ResourceManager.GetString("NorthernIrish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Korean.
        /// </summary>
        public static string NorthKorean {
            get {
                return ResourceManager.GetString("NorthKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Norwegian {
            get {
                return ResourceManager.GetString("Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistani.
        /// </summary>
        public static string Pakistani {
            get {
                return ResourceManager.GetString("Pakistani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestinian.
        /// </summary>
        public static string Palestinian {
            get {
                return ResourceManager.GetString("Palestinian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguayan.
        /// </summary>
        public static string Paraguayan {
            get {
                return ResourceManager.GetString("Paraguayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruvian.
        /// </summary>
        public static string Peruvian {
            get {
                return ResourceManager.GetString("Peruvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabian.
        /// </summary>
        public static string SaudiArabian {
            get {
                return ResourceManager.GetString("SaudiArabian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British / Scottish.
        /// </summary>
        public static string Scottish {
            get {
                return ResourceManager.GetString("Scottish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singaporean.
        /// </summary>
        public static string Singaporean {
            get {
                return ResourceManager.GetString("Singaporean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak / Slovakian.
        /// </summary>
        public static string Slovak {
            get {
                return ResourceManager.GetString("Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian / Slovene.
        /// </summary>
        public static string Slovenian {
            get {
                return ResourceManager.GetString("Slovenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somali / Somalian.
        /// </summary>
        public static string Somali {
            get {
                return ResourceManager.GetString("Somali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African.
        /// </summary>
        public static string SouthAfrican {
            get {
                return ResourceManager.GetString("SouthAfrican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korean.
        /// </summary>
        public static string SouthKorean {
            get {
                return ResourceManager.GetString("SouthKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lankan.
        /// </summary>
        public static string SriLankan {
            get {
                return ResourceManager.GetString("SriLankan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudanese.
        /// </summary>
        public static string Sudanese {
            get {
                return ResourceManager.GetString("Sudanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        public static string Swiss {
            get {
                return ResourceManager.GetString("Swiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian.
        /// </summary>
        public static string Syrian {
            get {
                return ResourceManager.GetString("Syrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwanese.
        /// </summary>
        public static string Taiwanese {
            get {
                return ResourceManager.GetString("Taiwanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzanian.
        /// </summary>
        public static string Tanzanian {
            get {
                return ResourceManager.GetString("Tanzanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisian.
        /// </summary>
        public static string Tunisian {
            get {
                return ResourceManager.GetString("Tunisian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugandan.
        /// </summary>
        public static string Ugandan {
            get {
                return ResourceManager.GetString("Ugandan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguayan.
        /// </summary>
        public static string Uruguayan {
            get {
                return ResourceManager.GetString("Uruguayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan.
        /// </summary>
        public static string Venezuelan {
            get {
                return ResourceManager.GetString("Venezuelan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British / Welsh.
        /// </summary>
        public static string Welsh {
            get {
                return ResourceManager.GetString("Welsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemeni / Yemenite.
        /// </summary>
        public static string Yemeni {
            get {
                return ResourceManager.GetString("Yemeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambian.
        /// </summary>
        public static string Zambian {
            get {
                return ResourceManager.GetString("Zambian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwean.
        /// </summary>
        public static string Zimbabwean {
            get {
                return ResourceManager.GetString("Zimbabwean", resourceCulture);
            }
        }
    }
}
