//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.OutResource", typeof(OutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Code.
        /// </summary>
        public static string Out_Code {
            get {
                return ResourceManager.GetString("Out_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Debt.
        /// </summary>
        public static string Out_Debt {
            get {
                return ResourceManager.GetString("Out_Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Month.
        /// </summary>
        public static string Out_Month {
            get {
                return ResourceManager.GetString("Out_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Paid.
        /// </summary>
        public static string Out_Paid {
            get {
                return ResourceManager.GetString("Out_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Reason.
        /// </summary>
        public static string Out_Reason {
            get {
                return ResourceManager.GetString("Out_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Total.
        /// </summary>
        public static string Out_Total {
            get {
                return ResourceManager.GetString("Out_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Trade Date.
        /// </summary>
        public static string Out_Trade_Date {
            get {
                return ResourceManager.GetString("Out_Trade_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Write Date.
        /// </summary>
        public static string Out_Write_Date {
            get {
                return ResourceManager.GetString("Out_Write_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Year.
        /// </summary>
        public static string Out_Year {
            get {
                return ResourceManager.GetString("Out_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Address.
        /// </summary>
        public static string Receiver_Address {
            get {
                return ResourceManager.GetString("Receiver_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name.
        /// </summary>
        public static string Receiver_Name {
            get {
                return ResourceManager.GetString("Receiver_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        public static string Staff_Name {
            get {
                return ResourceManager.GetString("Staff_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string Supplier_Name {
            get {
                return ResourceManager.GetString("Supplier_Name", resourceCulture);
            }
        }
    }
}
