//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaffCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaffCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.StaffCommonResource", typeof(StaffCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Status.
        /// </summary>
        public static string Auth_Status {
            get {
                return ResourceManager.GetString("Auth_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic salary.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number Party.
        /// </summary>
        public static string CardNumberParty {
            get {
                return ResourceManager.GetString("CardNumberParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker ID.
        /// </summary>
        public static string Checker_Id {
            get {
                return ResourceManager.GetString("Checker_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary coefficient.
        /// </summary>
        public static string CoefficientsSalary {
            get {
                return ResourceManager.GetString("CoefficientsSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new department.
        /// </summary>
        public static string CreateDep {
            get {
                return ResourceManager.GetString("CreateDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new staff info.
        /// </summary>
        public static string CreateStaff {
            get {
                return ResourceManager.GetString("CreateStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Approve.
        /// </summary>
        public static string Date_Approve {
            get {
                return ResourceManager.GetString("Date_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day at Party.
        /// </summary>
        public static string DayatParty {
            get {
                return ResourceManager.GetString("DayatParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day off.
        /// </summary>
        public static string Dayoff {
            get {
                return ResourceManager.GetString("Dayoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Started Making.
        /// </summary>
        public static string DayStartedMaking {
            get {
                return ResourceManager.GetString("DayStartedMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Wage.
        /// </summary>
        public static string DayWage {
            get {
                return ResourceManager.GetString("DayWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Birthday.
        /// </summary>
        public static string FatherBirthday {
            get {
                return ResourceManager.GetString("FatherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Full Name.
        /// </summary>
        public static string FatherFullName {
            get {
                return ResourceManager.GetString("FatherFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Job.
        /// </summary>
        public static string FatherJob {
            get {
                return ResourceManager.GetString("FatherJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card.
        /// </summary>
        public static string IndentityCard {
            get {
                return ResourceManager.GetString("IndentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a kindergartener.
        /// </summary>
        public static string IsAKindergartener {
            get {
                return ResourceManager.GetString("IsAKindergartener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is A Teacher.
        /// </summary>
        public static string IsATeacher {
            get {
                return ResourceManager.GetString("IsATeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Leaguer.
        /// </summary>
        public static string IsLeaguer {
            get {
                return ResourceManager.GetString("IsLeaguer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued by.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Job Detail.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Id.
        /// </summary>
        public static string Maker_Id {
            get {
                return ResourceManager.GetString("Maker_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Birthday.
        /// </summary>
        public static string MotherBirthday {
            get {
                return ResourceManager.GetString("MotherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Full Name.
        /// </summary>
        public static string MotherFullName {
            get {
                return ResourceManager.GetString("MotherFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Job.
        /// </summary>
        public static string MotherJob {
            get {
                return ResourceManager.GetString("MotherJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        public static string Record_Status {
            get {
                return ResourceManager.GetString("Record_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Grade.
        /// </summary>
        public static string SalaryGrade {
            get {
                return ResourceManager.GetString("SalaryGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string STAFF_ID {
            get {
                return ResourceManager.GetString("STAFF_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Code.
        /// </summary>
        public static string StaffNumber {
            get {
                return ResourceManager.GetString("StaffNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father phone.
        /// </summary>
        public static string TelephoneFather {
            get {
                return ResourceManager.GetString("TelephoneFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother phone.
        /// </summary>
        public static string TelephoneMother {
            get {
                return ResourceManager.GetString("TelephoneMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Contract.
        /// </summary>
        public static string TypeofContract {
            get {
                return ResourceManager.GetString("TypeofContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Increase Day.
        /// </summary>
        public static string WageIncreaseDay {
            get {
                return ResourceManager.GetString("WageIncreaseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Status.
        /// </summary>
        public static string WorkingStatus {
            get {
                return ResourceManager.GetString("WorkingStatus", resourceCulture);
            }
        }
    }
}
