//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentOverviewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentOverviewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindergartentManagerment.Resources.StudentOverviewResource", typeof(StudentOverviewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new student&apos;s physical info.
        /// </summary>
        public static string CreatePhysic {
            get {
                return ResourceManager.GetString("CreatePhysic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new student info.
        /// </summary>
        public static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Admission.
        /// </summary>
        public static string DateofAdmission {
            get {
                return ResourceManager.GetString("DateofAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Information.
        /// </summary>
        public static string FamilyInformation {
            get {
                return ResourceManager.GetString("FamilyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s birthday.
        /// </summary>
        public static string FatherBirthday {
            get {
                return ResourceManager.GetString("FatherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s job.
        /// </summary>
        public static string FatherJob {
            get {
                return ResourceManager.GetString("FatherJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s phone number.
        /// </summary>
        public static string FatherPhone {
            get {
                return ResourceManager.GetString("FatherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s birthday.
        /// </summary>
        public static string MotherBirthday {
            get {
                return ResourceManager.GetString("MotherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s job.
        /// </summary>
        public static string MotherJob {
            get {
                return ResourceManager.GetString("MotherJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s phone number.
        /// </summary>
        public static string MotherPhone {
            get {
                return ResourceManager.GetString("MotherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Subjects.
        /// </summary>
        public static string PrioritySubjects {
            get {
                return ResourceManager.GetString("PrioritySubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement (Example: Huynh Van A).
        /// </summary>
        public static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Year.
        /// </summary>
        public static string SchoolYear {
            get {
                return ResourceManager.GetString("SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information.
        /// </summary>
        public static string StudentInfomation {
            get {
                return ResourceManager.GetString("StudentInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
    }
}
