//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ASSETOVERVIEW
    {
        public int Asset_ID { get; set; }
        public string Asset_Code { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> Number { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string MaintenanceMode { get; set; }
        public string Unit { get; set; }
        public string Record_Status { get; set; }
        public string Maker_ID { get; set; }
        public Nullable<System.DateTime> Create_DT { get; set; }
        public string Auth_Status { get; set; }
        public string Checker_ID { get; set; }
        public Nullable<System.DateTime> Approve_DT { get; set; }
    }
}
