//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartentManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_MENUCOMPONENT
    {
        public int Menu_ID { get; set; }
        public string FoodType { get; set; }
        public string MealPeriod { get; set; }
        public string DishesList { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Notes { get; set; }
        public string Record_Status { get; set; }
        public string Maker_ID { get; set; }
        public System.DateTime Create_DT { get; set; }
        public string Auth_Status { get; set; }
        public string Checker_ID { get; set; }
        public Nullable<System.DateTime> Approve_DT { get; set; }
    }
}
